# 使用 Node.js 镜像
FROM node:20-alpine AS runner
WORKDIR /app

# 复制必要文件
COPY .next/standalone ./
COPY .next/static ./.next/static
COPY public ./public

# 暴露端口
EXPOSE 3000
ENV PORT 3000

# 运行命令
CMD ["node", "server.js"]